// <auto-generated />
using EveMoonminingTool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EveMoonminingTool.Migrations
{
    [DbContext(typeof(EveMoonminingToolContext))]
    [Migration("20180802150656_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EveMoonminingTool.Models.MiningJob", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Corp");

                    b.Property<DateTime>("Day");

                    b.Property<int>("EstimatedValue");

                    b.Property<int>("OreID");

                    b.Property<string>("OreType");

                    b.Property<string>("Pilot");

                    b.Property<int>("SystemID");

                    b.Property<float>("Volumen");

                    b.HasKey("ID");

                    b.ToTable("MiningJob");
                });
#pragma warning restore 612, 618
        }
    }
}
